Weakening range of causal relation between processes. This may be temporary. See https://github.com/oborel/obo-relations/issues/524
oborel/obo-relations pull request #525
Opened 2021-11-18 17:23 UTC by cmungall

2021-11-18 17:40 UTC, matentzn approved these changes

2021-11-18 17:41 UTC, matentzn commented on src/ontology/ro-edit.owl
> +ObjectPropertyDomain(obo:RO_0002501 ObjectUnionOf(obo:BFO_0000015 obo:BFO_0000019))
Its odd you go from BFO:3 to BFO:15 or BFO:19. Is that intended?

2021-11-18 17:41 UTC, matentzn requested changes
Just double check my comment

2021-11-19 00:51 UTC, balhoff requested changes
Just same question as Nico, otherwise looks good.

2021-11-22 20:09 UTC, cmungall commented
occurent => process or quality.

yes this is intentional. Are there any useful siblings of process?

2021-12-07 18:34 UTC, balhoff approved these changes

2021-12-07 18:46 UTC, balhoff requested changes
If we're going to do this, we will need to do the same to 'precedes' and 'temporally related to', and 'preceded by', etc.

2021-12-17 16:32 UTC, balhoff commented
Please hold off on merging this; I am going to make an alternative PR.

2022-01-11 17:48 UTC, closed without merging