add 'synapses restricted to region'
oborel/obo-relations pull request #755
Opened 2023-08-17 12:25 UTC by Clare72

fixes #754

2023-08-17 13:33 UTC, gouttegd submitted a review, later dismissed

2023-08-18 08:55 UTC, anitacaron requested changes

2023-08-18 08:55 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +
Please, add an example of usage (annotation IAO:0000112).

2023-08-18 09:27 UTC, Clare72 commented
also adding property chain over part_of (if neuron has synapses restricted to part of A, its synapses are also restricted to A)

2023-08-18 09:43 UTC, anitacaron requested changes

2023-08-18 09:43 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +AnnotationAssertion(dc:date obo:RO_0013010 "2023-08-17T12:17:24Z"^^xsd:dateTime)
Please use the annotations from `terms: <http://purl.org/dc/terms/>`

2023-08-18 13:57 UTC, cmungall commented
Hmm, this is for smuggling in universal quantifications as existentials.

Owl already has a way of saying synapsed to ONLY region X.

We already snuggle with taxon constraints, there are many impracticalities and traps when using universals directly (I go as far as to say it's an anti pattern). For TCs we encode shortcuts. Should we do the same here?

Cc @d

2023-08-18 13:58 UTC, cmungall commented
Cc @dosumis

2023-08-18 14:06 UTC, cmungall commented
I'm not going to correct my typo above as I quite like the idea of snuggly taxon constraints 🧸

2023-09-11 15:21 UTC, addiehl commented
Please incorporate the comments from issue https://github.com/oborel/obo-relations/issues/754.

2024-02-07 09:48 UTC, Clare72 commented
@addiehl @anitacaron are you happy with this now?

2024-02-09 09:45 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +AnnotationAssertion(terms:creator obo:RO_0013010 <https://orcid.org/0000-0002-1373-1705>)
Please use `terms:contributor` instead of `terms:creator`. I can make the change here.

2024-02-09 10:18 UTC, anitacaron approved these changes
Technically, I approve. It still needs an ontology review.

2024-12-02 16:40 UTC, cmungall approved these changes

2024-12-02 17:02 UTC, merged