collected during relation
oborel/obo-relations pull request #759
Opened 2023-10-09 14:56 UTC by ddooley

A relation between a material entity and an occurent in which the specimen is collected during the existence of the occurent.

2023-10-10 19:16 UTC, wdduncan commented
'occurent' should be 'occurrent' (needs another 'r').

Perhaps be consistent in the use of 'material entity'? Information about 'specimen' could be in a one sentence gloss. E.g.:  
```
A relation between a material entity and an occurrent in which the material entity is collected during the existence of the occurrent. The material entity is a specimen that collected for scientific purposes.
```

2024-01-22 03:06 UTC, ddooley commented
I made suggested change.  This can now be approved and closed!

2024-01-22 19:58 UTC, anitacaron submitted a review, later dismissed
Technically approved. It still needs ontology approval.

2024-02-09 10:27 UTC, anitacaron submitted a review, later dismissed
Technically approved. It still needs ontology approval.

2024-04-22 15:47 UTC, cmungall commented on src/ontology/ro-edit.owl
> +ObjectPropertyRange(obo:RO_0017502 obo:BFO_0000003)
general observation: this is occurrent, which is above the shoreline in COB. See #780. This comment is not to block the PR: clearly we have a precedent for using occurrent already

2024-05-08 05:12 UTC, ddooley commented on src/ontology/ro-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:RO_0017502 "A relation between a material entity and an occurrent in which the material entity is collected during the existence of the occurrent. The material
Done!

2024-05-08 05:13 UTC, ddooley reviewed
Good to go!

2024-05-08 08:13 UTC, anitacaron requested changes

2024-05-08 08:13 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +Declaration(Class(obo:PATO_0001470))
Why this PATO term was included in the edit file?

2024-07-15 09:04 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +Declaration(Class(obo:PATO_0001470))
I don't think so. :) I've removed it anyway.

2024-07-15 09:07 UTC, anitacaron approved these changes
Technically, I approve. Still need to have an ontology review,

2024-08-12 15:06 UTC, cmungall approved these changes

2024-08-12 15:43 UTC, merged