adding eco relations definitions
oborel/obo-relations pull request #762
Opened 2023-10-19 20:04 UTC by diatomsRcool

Adding definitions for 

- eats
- is eaten by
- provide nutrients for
- aquires nutrients from
- parasite of
- parasitized by
- has pathogen
- pathogen of
For issue #646

2023-10-19 20:04 UTC, diatomsRcool commented
I'm sure these need some word-smithing.....

2023-10-25 05:46 UTC, ddooley commented on src/ontology/ro-edit.owl
> +Prefix(dc:=<http://purl.org/dc/terms/>)
I think RO now has it that prefix "terms" => http://purl.org/dc/terms/

2023-10-25 05:53 UTC, ddooley commented on src/ontology/ro-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:RO_0002469 "A feeding relationship where one organism provides nutrition for another organism without being directly consumed. Examples include but are not lim
Where inverse relations occur I recall RO is moving towards the pattern of just saying in defn. that "inverse of [inverse relation label]".

2023-10-25 17:27 UTC, diatomsRcool commented
Yes, Sierra, I think the "acquires nutrients from" would work.

2023-10-27 16:56 UTC, anitacaron requested changes

2023-10-27 16:56 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:RO_0002557 "A host interaction where the smaller of the two members of a symbiosis is causes a disease in the larger member")
Duplicated definitions: need to remove one of them.

2023-10-27 16:56 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +Declaration(AnnotationProperty(dc:title))
Could you update the branch from master, please?

2023-10-27 17:01 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +Declaration(AnnotationProperty(dc:title))
Or maybe change the prefix in your Protégé?

2023-11-01 21:55 UTC, ddooley commented
The FoodOn team of course is interested in some of these term definitions, namely "eats" and "is eaten by".  For eats, "A feeding relationship where one organism consumes another (either in whole or in part) through a type of mouth or other oral opening." We were just wondering if there is a more limiting word or label that conveys semantics of feeding on a single organism (or piece) directly.  More generally people "eat" salt, water, and multi-component foods, but this isn't included in the trophic sense of "eats". However we haven't been able to think of a simple solution to distinguish eating broadly vs the specific animal or part case.

2023-11-01 22:04 UTC, ddooley commented
There's a similar comment for the "aquires nutrients from" shortcut relation.  I see cattle feed is often supplemented with salt.  "Animal feed salt is an essential addition to animal feed. Salt maintains the mineral balance of the animals at the right level and keeps your livestock healthy. It is advisable to opt for sea salt because this type of salt also contains additional essential minerals and trace elements."  This relation as proposed requires us to use some other relation to connect an organism and other material entity nutritional sources.

2023-11-02 13:03 UTC, diatomsRcool commented
I struggled with similar issues as well. Unfortunately, interactions are separated as abiotic/biotic and biotic/biotic higher up in the hierarchy. We would need two "eats" one for biotic/biotic and one for abiotic/biotic - but this isn't that good as many foods are a combination. The line between abiotic/biotic isn't always very sharp. What if we elevate the "eats" and "acquires nutrients from" relations to be children of biotically interacts with? I can change the definition to include abiotic foods.

2023-11-02 17:19 UTC, ddooley commented
That sounds like a good solution!  (And I can see that these relations can operate in parallel with the other ones like "kills" and "preys on").

2023-11-02 19:50 UTC, diatomsRcool commented
Do we think "eats" should be a child of "acquires nutrients from"? One possible reason we cannot do that is organisms that eat rocks for the purpose of helping with digestion.

2023-11-02 21:36 UTC, ddooley commented
Indeed, eating isn't always motivated by nutritional intake.  Rock is a good eample.  Also, arguably caffeine isn't doing anything for the consumer, but its a motivator for eating.

2023-11-03 10:49 UTC, anitacaron commented on src/ontology/ro-edit.owl
> +Declaration(AnnotationProperty(dc:title))
@diatomsRcool, do you need help with fixing it?

2023-11-03 13:33 UTC, diatomsRcool commented
definitions updated

2023-11-03 15:36 UTC, wdduncan commented
> Do we think "eats" should be a child of "acquires nutrients from"? One possible reason we cannot do that is organisms that eat rocks for the purpose of helping with digestion.

Should `acquires nutrients from` be a child of `eats`? The defn for `eats` mentions oral openings. Doesn't seem like this would apply to plants, but plans to `acquires nutrients from` some source.

2023-11-03 15:58 UTC, ddooley commented
As well, covering all cases, Parenteral / intravenous feeding enables nutrients to be collected directly, so 'acquires nutrients from' is not a subclass of eats on that count either.

Is eats meant to be restricted to animal organisms?  The only other example I can think of are coniverous plants - e.g. venus fly traps.  But there digestive processes happen at surface of plant?

2023-11-06 16:37 UTC, anitacaron approved these changes
Technically, it's approved, but it still needs an ontology review.

2024-02-26 16:56 UTC, cmungall approved these changes

2024-02-29 10:49 UTC, merged