2024-02-12 Release
oborel/obo-relations pull request #788
Opened 2024-02-12 17:17 UTC by anitacaron

2024-02-12 19:32 UTC, balhoff requested changes
@anitacaron I think there is a problem with the changes from #761. @pgaudet did not mean to put the terms under 'regulates' (please let me know if I'm misreading the diff). Is there time to fix that before release?

2024-02-12 19:44 UTC, anitacaron commented
@balhoff, that's fine. I'll wait to fix this in another PR. But I've checked the [issue linked](https://github.com/oborel/obo-relations/issues/760) to that PR, and it's consistent.

2024-02-13 15:55 UTC, wdduncan commented
@anitacaron Most everything looks fine. However, I noticed that I am not included in the orcidio import, although I added myself as part of the [owns/owned by PR](https://github.com/oborel/obo-relations/pull/705).   
Is it possible for you to merge that PR as part of this release?

2024-02-13 16:10 UTC, anitacaron commented
@wdduncan sorry, someone needs to approve that PR first 😬

2024-02-13 16:21 UTC, matentzn approved these changes
Looks great!

2024-02-13 16:21 UTC, matentzn commented on src/ontology/subsets/ro-mereotopology.obo
> +property_value: IAO:0000112 "A caterpillar walking on the surface of a leaf is adjacent_to the leaf, if one of the caterpillar appendages is touching the leaf. In contrast, a butterfly flying close t
.... value should be URL. not a blocker, just a comment.

2024-02-13 16:25 UTC, anitacaron commented
@wdduncan, no worries, all changes to add you into orcidio_import are in your PR.

2024-02-15 09:32 UTC, merged